version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: queue
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: buddy
      RABBITMQ_DEFAULT_PASS: buddy
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq-init.sh:/docker-entrypoint-initdb.d/rabbitmq-init.sh
    networks:
      - rabbitmq_network
    restart: always

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local